import json
import argparse
import sys


def ckks_context_params(logN: int) -> dict:
    return {"btp_scale_bits": 50, "first_mod_bits": 53}


def gen_cpp_config(placement, num_layers=12, logN=16):
    dc = placement.get("decoder_config")
    route = placement["route"]
    bootstraps = placement["bootstraps"]
    latency = placement["end_to_end_latency"]
    max_level = placement["max_level"]

    if not dc:
        dc = {
            "norm1_btp_level": max_level,
            "norm1_target_level": max_level,
            "cache_btp_level": max_level,
            "attn_btp_level": max_level,
            "attn_v_btp_level": max_level,
            "norm2_btp_level": max_level,
            "norm2_target_level": max_level,
            "gelu_btp_level": max_level,
            "down_btp_level": max_level,
        }

    kSoftmaxMinRemaining = 9  # exp_r(7) + 1 (EvalMult) + 1 (safety)
    needs_fix = False
    if dc.get("gelu_btp_level", max_level) < max_level:
        needs_fix = True
    if dc.get("attn_btp_level", kSoftmaxMinRemaining) < kSoftmaxMinRemaining:
        needs_fix = True
    if needs_fix:
        dc = dict(dc)
        dc["gelu_btp_level"] = max(dc.get("gelu_btp_level", max_level), max_level)
        dc["attn_btp_level"] = max(dc.get("attn_btp_level", kSoftmaxMinRemaining),
                                   kSoftmaxMinRemaining)

    lines = []
    lines.append("// Auto-generated by gen_config.py from bootstrap placement optimizer")
    lines.append(f"// End-to-end latency: {latency:.2f} s  ({num_layers} decoder layers)")
    lines.append(f"// Input level: {placement['input_level']}, "
                 f"Output level: {placement['output_level']}")
    lines.append(f"// Inter-decoder bootstraps: {len(bootstraps)}")

    # Annotate the MHA/FFN pipeline with BTP positions
    ann = dc.get("annotations", {})
    if ann.get("mha_route"):
        mha_steps = [f"{s['op']}@{s['input_level']}"
                     + (" [BTP]" if s.get("note") else "")
                     for s in ann["mha_route"]]
        lines.append(f"// MHA pipeline: {' → '.join(mha_steps)}")
    if ann.get("ffn_route"):
        ffn_steps = [f"{s['op']}@{s['input_level']}"
                     + (" [BTP]" if s.get("note") else "")
                     for s in ann["ffn_route"]]
        lines.append(f"// FFN pipeline: {' → '.join(ffn_steps)}")
    if ann.get("total_btps_per_decoder"):
        lines.append(f"// BTPs per decoder: {ann['total_btps_per_decoder']} total "
                     f"({ann.get('norm_internal_btps', '?')} per Norm × 2, "
                     f"{ann.get('gelu_internal_btps', '?')} GELU, "
                     f"{ann.get('mha_inter_btps', '?')} MHA-inter, "
                     f"{ann.get('ffn_inter_btps', '?')} FFN-inter)")

    ctx = ckks_context_params(logN)

    lines.append(f"//")
    lines.append(f"// bootstrap_to() is conditional — only fires when remaining depth")
    lines.append(f"// is below the target level. Targets are set to give each sub-circuit")
    lines.append(f"// the maximum available depth, minimizing internal DepthGuard BTPs.")
    lines.append(f"")
    lines.append(f"#pragma once")
    lines.append(f'#include "gpt2.h"')
    lines.append(f"")
    lines.append(f"// FHE context parameters — owned by gen_config.py, do not edit by hand.")
    lines.append(f"// Regenerate with: uv run python gen_config.py <placement.json> --logN {logN} -o include/gpt2_optimized_config.h")
    lines.append(f"static constexpr int kGPT2ConfigLogN       = {logN};")
    lines.append(f"static constexpr int kGPT2BtpScaleBits     = {ctx['btp_scale_bits']};")
    lines.append(f"static constexpr int kGPT2FirstModBits      = {ctx['first_mod_bits']};")
    lines.append(f"")
    lines.append(f"inline GPT2ModelConfig make_gpt2_optimized_config() {{")
    lines.append(f"    GPT2ModelConfig cfg;")
    lines.append(f"    cfg.num_layers = {num_layers};")
    lines.append(f"    cfg.layers.resize({num_layers});")
    lines.append(f"")
    lines.append(f"    for (int i = 0; i < {num_layers}; ++i) {{")
    lines.append(f"        cfg.layers[i].norm1_btp_level    = {dc['norm1_btp_level']};"
                 f"  // BTP before Norm1")
    lines.append(f"        cfg.layers[i].norm1_target_level = {dc['norm1_target_level']};"
                 f"  // DepthGuard refresh inside NR/GS")
    lines.append(f"        cfg.layers[i].cache_btp_level    = {dc.get('cache_btp_level', dc['norm1_btp_level'])};"
                 f"  // BTP k,v before cache update (keeps cache at low level)")
    lines.append(f"        cfg.layers[i].attn_btp_level     = {dc['attn_btp_level']};"
                 f"  // BTP after QK^T, before Softmax")
    lines.append(f"        cfg.layers[i].attn_v_btp_level   = {dc['attn_v_btp_level']};"
                 f"  // BTP before AttnV (0=skip)")
    lines.append(f"        cfg.layers[i].norm2_btp_level    = {dc['norm2_btp_level']};"
                 f"  // BTP before Norm2")
    lines.append(f"        cfg.layers[i].norm2_target_level = {dc['norm2_target_level']};"
                 f"  // DepthGuard refresh inside NR/GS")
    lines.append(f"        cfg.layers[i].gelu_btp_level     = {dc['gelu_btp_level']};"
                 f"  // BTP after Up, before GELU")
    lines.append(f"        cfg.layers[i].down_btp_level     = {dc['down_btp_level']};"
                 f"  // BTP before Down (0=skip)")
    lines.append(f"    }}")
    lines.append(f"")

    # Per-layer taylor_rescale from profiled config
    lines.append(f"    // Per-layer taylor_rescale (from estimate_ranges.py)")
    lines.append(f"    static const double rescales[{num_layers}] = {{")
    lines.append(f"        0.19271061, 0.01123577, 0.00085924, 0.00005702,")
    lines.append(f"        0.00004874, 0.00004363, 0.00004080, 0.00003925,")
    lines.append(f"        0.00003833, 0.00003779, 0.00003752, 0.00003747,")
    lines.append(f"    }};")
    lines.append(f"    for (int i = 0; i < {num_layers}; ++i) {{")
    lines.append(f"        NormConfig nc = NORM_ENCLLM_GPT2;")
    lines.append(f"        nc.taylor_rescale = rescales[i];")
    lines.append(f"        cfg.layers[i].norm1_cfg = nc;")
    lines.append(f"        cfg.layers[i].norm2_cfg = nc;")
    lines.append(f"    }}")
    lines.append(f"    cfg.final_norm_cfg = NORM_ENCLLM_GPT2;")
    lines.append(f"    cfg.final_norm_cfg.taylor_rescale = rescales[{num_layers - 1}];")
    lines.append(f"")
    lines.append(f"    return cfg;")
    lines.append(f"}}")
    lines.append(f"")
    lines.append(f"// Lazy init to avoid static initialization order issues")
    lines.append(f"inline const GPT2ModelConfig& gpt2_optimized_config() {{")
    lines.append(f"    static const GPT2ModelConfig cfg = make_gpt2_optimized_config();")
    lines.append(f"    return cfg;")
    lines.append(f"}}")

    return "\n".join(lines)


def gen_json_config(placement, num_layers=12):
    """Generate a JSON config that main.cu could load at runtime."""
    dc = placement.get("decoder_config", {})
    return {
        "model": placement["model"],
        "latency": placement["end_to_end_latency"],
        "num_layers": num_layers,
        "max_level": placement["max_level"],
        "decoder_config": dc,
        "route": placement["route"],
        "bootstraps": placement["bootstraps"],
    }


def main():
    parser = argparse.ArgumentParser(
        description="Convert bootstrap placement JSON to GPT-2 C++ config"
    )
    parser.add_argument("placement_json",
                        help="Path to *_placement.json from bootstrap.py")
    parser.add_argument("-o", "--output", default="",
                        help="Output file (default: stdout)")
    parser.add_argument("--format", choices=["cpp", "json"], default="cpp",
                        help="Output format (default: cpp)")
    parser.add_argument("--num-layers", type=int, default=12,
                        help="Number of decoder layers")
    parser.add_argument("--logN", type=int, default=0,
                        help="Ring dimension log2 — sets btp_scale_bits/first_mod_bits "
                             "(default: read from placement JSON, fallback 16)")
    args = parser.parse_args()

    with open(args.placement_json) as f:
        placement = json.load(f)

    # Resolve logN: CLI > placement JSON > default 16
    logN = args.logN or placement.get("logN", 16)

    if args.format == "cpp":
        result = gen_cpp_config(placement, args.num_layers, logN=logN)
    else:
        result = json.dumps(gen_json_config(placement, args.num_layers), indent=2)

    if args.output:
        with open(args.output, "w") as f:
            f.write(result + "\n")
        print(f"Config written to {args.output}")
    else:
        print(result)


if __name__ == "__main__":
    main()
