// Auto-generated by gen_config.py from bootstrap placement optimizer
// End-to-end latency: 26258.80 s  (12 decoder layers)
// Input level: 13, Output level: 13
// Inter-decoder bootstraps: 11
// MHA pipeline: Norm1@13 → QKV_x3@6 [BTP] → QK_Softmax@4 [BTP] → AttnV@4 → O_proj@2 [BTP]
// FFN pipeline: Norm2@0 → Up@4 → GELU@2 [BTP] → Down@2
// BTPs per decoder: 173 total (75 per Norm × 2, 19 GELU, 3 MHA-inter, 1 FFN-inter)
//
// bootstrap_to() is conditional — only fires when remaining depth
// is below the target level. Targets are set to give each sub-circuit
// the maximum available depth, minimizing internal DepthGuard BTPs.

#pragma once
#include "gpt2.h"

// FHE context parameters — owned by gen_config.py, do not edit by hand.
// Regenerate with: uv run python gen_config.py <placement.json> --logN 16 -o include/gpt2_optimized_config.h
static constexpr int kGPT2ConfigLogN       = 16;
static constexpr int kGPT2BtpScaleBits     = 50;
static constexpr int kGPT2FirstModBits      = 53;

inline GPT2ModelConfig make_gpt2_optimized_config() {
    GPT2ModelConfig cfg;
    cfg.num_layers = 12;
    cfg.layers.resize(12);

    for (int i = 0; i < 12; ++i) {
        cfg.layers[i].norm1_btp_level    = 13;  // BTP before Norm1
        cfg.layers[i].norm1_target_level = 13;  // DepthGuard refresh inside NR/GS
        cfg.layers[i].cache_btp_level    = 13;  // BTP k,v before cache update (keeps cache at low level)
        cfg.layers[i].attn_btp_level     = 9;  // BTP after QK^T, before Softmax
        cfg.layers[i].attn_v_btp_level   = 0;  // BTP before AttnV (0=skip)
        cfg.layers[i].norm2_btp_level    = 13;  // BTP before Norm2
        cfg.layers[i].norm2_target_level = 13;  // DepthGuard refresh inside NR/GS
        cfg.layers[i].gelu_btp_level     = 13;  // BTP after Up, before GELU
        cfg.layers[i].down_btp_level     = 0;  // BTP before Down (0=skip)
    }

    // Per-layer taylor_rescale (from estimate_ranges.py)
    static const double rescales[12] = {
        0.19271061, 0.01123577, 0.00085924, 0.00005702,
        0.00004874, 0.00004363, 0.00004080, 0.00003925,
        0.00003833, 0.00003779, 0.00003752, 0.00003747,
    };
    for (int i = 0; i < 12; ++i) {
        NormConfig nc = NORM_ENCLLM_GPT2;
        nc.taylor_rescale = rescales[i];
        cfg.layers[i].norm1_cfg = nc;
        cfg.layers[i].norm2_cfg = nc;
    }
    cfg.final_norm_cfg = NORM_ENCLLM_GPT2;
    cfg.final_norm_cfg.taylor_rescale = rescales[11];

    return cfg;
}

// Lazy init to avoid static initialization order issues
inline const GPT2ModelConfig& gpt2_optimized_config() {
    static const GPT2ModelConfig cfg = make_gpt2_optimized_config();
    return cfg;
}
